# Generated by Django 5.2.7 on 2025-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_add_region_and_dish'),
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Related recipes for this region', related_name='map_pins', to='mealplans.recipe'),
        ),
    ]
