# Generated by Django 5.2.7 on 2025-11-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(default='Jikoni Journals – 30-Day Dinner Meal Plan', max_length=200)),
                ('compiled_by', models.CharField(default='Charity Mutisya', max_length=100)),
                ('shopping_list', models.TextField(help_text='Comma-separated list of shopping items for the week.')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(help_text='List each ingredient on a new line.')),
                ('method', models.TextField(help_text='List each step on a new line.')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='mealplans.week')),
            ],
            options={
                'ordering': ['week__week_number', 'day'],
            },
        ),
    ]
