# Generated by Django 5.2.7 on 2026-01-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snack', 'Snack')], default='meal', max_length=10),
        ),
    ]
