# Generated by Django 5.2.7 on 2026-01-02 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_payment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='tour_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meal_plan_recipe',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
    ]
